config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  resources :weddings, only: [:show] do
    resources :families
    resources :desks
    resources :guest_desks
    resources :guests, except: :delete
    member do
      post 'assign_guests'
      get 'guest_desks/affect', to: 'guest_desks#affect'
      get "sitting_plan", to: "weddings#sitting_plan"
    end
  end


  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'

  # get "desks/new", to: "desks#new"
  get "guests", to: "guests#index"
  get "guest/new", to: "guest#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/desk.rb
class Desk < ApplicationRecord
  belongs_to :wedding
  has_many :guest_desks
  has_many :guests, through: :guest_desks

  def taken_seats
    guests.count
  end

  def remaining_seats
    capacity - taken_seats
  end

  def status
    capacity == guests.count ? "COMPLETE" : "PENDING"
  end
end

app/models/family.rb
class Family < ApplicationRecord
  include Abyme::Model

  has_many :guests, dependent: :destroy
  abymize :guests, permit: :all_attributes

  validates :name, presence: true

  def family?
    guests.map(&:last_name).uniq.compact.count == 1
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :family
  belongs_to :spouse
  # belongs_to :guest_desk
  # belongs_to :desk, through: :guest_desk
  has_many :guest_desks, dependent: :destroy
  has_many :desks, through: :guest_desk

  validates :first_name, presence: true

  GENDER = ["woman", "man"]

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/models/guest_desk.rb
class GuestDesk < ApplicationRecord
  belongs_to :desk
  belongs_to :guest
end

app/models/spouse.rb
class Spouse < ApplicationRecord
  belongs_to :wedding
  has_many :guests, dependent: :destroy

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, :password, presence: true
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wedding_accesses, dependent: :destroy
  has_many :weddings, through: :wedding_accesses
end

app/models/wedding.rb
class Wedding < ApplicationRecord
  has_many :spouses, dependent: :destroy
  has_many :guests, through: :spouses
  has_many :desks, dependent: :destroy
  has_many :families, through: :guests
  has_many :guest_desks, through: :desks

  geocoded_by :city_hall
  after_validation :geocode, if: :will_save_change_to_city_hall?

  def countdown_date
    # Jan 5, 2024 15:37:25
    # debugger
    year, month, day_num = day.to_s.split('-')
    "#{Date::MONTHNAMES[month.to_i].first(3).capitalize} #{day_num}, #{year} 00:00:00"
  end

  def not_affected_guests
    assigned_guests = guests.select do |guest|
      !guest.guest_desks.empty?
    end
    guests - assigned_guests
  end
end

app/models/wedding_access.rb
class WeddingAccess < ApplicationRecord
  belongs_to :user
  belongs_to :wedding
  #validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  def index
    @desk = Desk.new # Needed to instantiate the form_with
    @wedding = Wedding.find(params[:wedding_id])
    @desks = @wedding.desks
    @desk = Desk.new
  end

  def new
    @wedding = Wedding.find(params[:wedding_id])
    @desk = Desk.new
  end

  def create
    @desk = Desk.new(desk_params)
    @desk.wedding = current_user.weddings.last
    if @desk.save
      selected_guest_ids = params[:desk][:pending_guests]
      @desk.guests << Guest.where(id: selected_guest_ids) if selected_guest_ids.present?
      redirect_to action: "index"
    else
      render :new
    end
  end

  def show
    @wedding = Wedding.find(params[:wedding_id])
    @desk = Desk.find(params[:id])
  end

  def edit
    @wedding = Wedding.find(params[:wedding_id])
    @desk = Desk.find(params[:id])
  end

  def update
    @desk = Desk.find(params[:id])
    if @desk.update(desk_params)
      redirect_to action: "index", notice: 'Table was successfully updated.'
    else
      render :edit
    end
  end

  def assign_guests
    @desk = Desk.find(params[:id])
    @guests = Guest.where(id: params[:desk][:guest_ids])

    if @desk.guests << @guests
      respond_to do |format|
        format.js
      end
    else
      # Handle errors
    end
  end

  private

  def desk_params
    params.require(:desk).permit(:name, :capacity, :shape)
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController

  def index
    @family = Family.new # Needed to instantiate the form_with
    @wedding = Wedding.find(params[:wedding_id])
    all_families = @wedding.families.uniq
    all_families.delete_at(all_families.index(Family.find_by(name: "Epoux")))
    @families = all_families
    @guests = @wedding.guests
  end

  def show
    @wedding = Wedding.find(params[:wedding_id])
  end


  def new
    @wedding = Wedding.find(params[:wedding_id])
    @family = Family.new # Needed to instantiate the form_with
    @spouses = @wedding.spouses
  end

  def create
    @family = Family.new(family_params)
    # debugger
    if @family.save # Will raise ActiveModel::ForbiddenAttributesError
      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @wedding = Wedding.find(params[:wedding_id])
    @family = Family.find(params[:id])
  end

  def update
    @family = Family.find(params[:id])
    if @family.update(family_params)
      redirect_to action: "index", notice: 'Family was successfully updated.'
    else
      render :edit
    end
  end

  private

  def family_params
    params.require(:family).permit(abyme_attributes, :name, :email)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @wedding = Wedding.find(params[:wedding_id])
    # @guests = @wedding.guests.all
    @guests = Guest.all
    # @family = Family.new
  end

  def new
    @guest = Guest.new # Needed to instantiate the form_with
  end

  def create
    @wedding = Wedding.find(params[:wedding_id])
    @guest = Guest.new(guest_params)
    @guest.save! # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to wedding_families_path(@wedding)
  end

  def destroy
    @wedding = Wedding.find(params[:wedding_id])
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to wedding_families_path(@wedding)
  end

  private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :age_category, :gender, :witness, :status, :family_id, :spouse_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @wedding = current_user.weddings.last
    
    @markers = [
      {
        lat: @wedding.latitude,
        lng: @wedding.longitude
      }
    ]
  end
end

app/controllers/spouses_controller.rb
class SpousesController < ApplicationController
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  def show
  end

  def sitting_plan
    @wedding = Wedding.find(params[:id])
    @guests = @wedding.guests
    @assigned_guests = @guests.select do |guest|
      !guest.guest_desks.empty?
    end
    @pending_guests = @guests - @assigned_guests
    @desks = @wedding.desks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/guest_desks_helper.rb
module GuestDesksHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spouses_helper.rb
module SpousesHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/desks/_available_tables.html.erb
<% @desks.each do |desk| %>
  <li class="list-group-item">
    <p> <%= desk.name %> : <%= desk.guests.count %> / <%= desk.capacity %> places </p>

    <%= simple_form_for ([@wedding, desk], remote: true) do |f| %>
      <div class="form-group">
        <%= f.collection_select :guest_ids, @pending_guests, :id, :full_name, {}, { multiple: true, class: 'form-control' } %>
      </div>
      <%= f.submit "Assign", class: "btn btn-primary btn-sm" %>
    <% end %>

  </li>
<% end %>

app/views/desks/_desk_show.html.erb
<div class="desk-show offcanvas offcanvas-end <%= "show" if params["desk_id"].present? && params["desk_id"].to_i == desk.id %>"
      tabindex="-1"
      data-bs-backdrop="false"
      aria-modal="true"
      role="dialog"
      id="offcanvasEdit-<%= desk.id %>"
      aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">

    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body ">
    <div class="desk-show-top">
      <span class="tab"><%= desk.status %></span>
      <%= link_to edit_wedding_desk_path(wedding, desk) do %>
        <i class="fa-solid fa-pencil"></i>
      <% end %>
    </div>
    <div class="desk-show-title">
      <div class="desk-card-left">
        <h3><%= desk.name %></h3>
        <div class="desk-features">
          <div class="desk-feature">
            <%= image_tag "#{desk.shape.downcase}.svg" %>
            <p><%= desk.shape.capitalize %> table</p>
          </div>
          <div class="desk-feature">
            <%= image_tag "groupe.svg" %>
            <p>Max. <%= desk.capacity %> guests</p>
          </div>
        </div>
      </div>
      <div class="right">
        <div class="desk-gauge-container">
          <div class="desk-gauge">
            <% desk.taken_seats.times do  %>
              <div class="desk-gauge-item taken"></div>
            <% end %>
            <% desk.remaining_seats.times do  %>
              <div class="desk-gauge-item"></div>
            <% end %>
          </div>

          <% if desk.remaining_seats.zero? %>
            <p class="desk-gauge-info"><strong>COMPLETE</strong></p>
          <% else %>
            <p class="desk-gauge-info"><strong><%= desk.remaining_seats %></strong> seats left</p>
          <% end %>

        </div>
      </div>
    </div>
    <div class="desk-show-guests">
      <p>Your <%= desk.guests.count %> guests around this table</p>
      <ul class="desk-guests-list">
        <% desk.guests.sort_by(&:last_name).each do |guest| %>
          <li>
            <%= image_tag "#{guest.gender.downcase}.png" %>
            <p><strong><%= guest.first_name %></strong> <%= guest.last_name %>

              <% if guest.fullname == guest.spouse.fullname %>
                <%= guest.gender == "man" ? "🤵" : "👰" %>
              <% elsif guest.witness %>
                - <%= guest.gender == "man" ? "🙋‍♂️" : "🙋‍♀️" %> <%= guest.spouse.first_name %>'s witness
              <% else %>
                (<%= guest.family.name %>'s group) - invited by <%= guest.spouse.first_name %>
              <% end %>


            </p>
          </li>
        <% end %>
      </ul>
    </div>

    <% unless desk.status == "COMPLETE" %>
      <p><strong>Add a guest to this table</strong></p>
      <%= simple_form_for [wedding, GuestDesk.new] do |f| %>
      <div class="desk-add-guest">
        <%= f.input :desk_id, as: :hidden, input_html: {value: desk.id} %>
        <%= f.input :guest_id, as: :select, collection: wedding.not_affected_guests, label_method: :fullname, prompt: "Please select a guest to add at this table", label: false %>
        <button type="submit" class="tab">+</button>
      <% end %>
      </div>

    <% end %>

  </div>
</div>

app/views/desks/_pending_guests.html.erb
<% @pending_guests.each do |pending_guest| %>
  <li class="list-group-item">
    <p> <%= pending_guest.full_name %> </p>

    <%= simple_form_for [@wedding, GuestDesk.new] do |f| %>
      <div class="form-group">
        <%= f.collection_select :desk_id, @desks, :id, :name, {}, { multiple: false, class: 'form-control' } %>
      </div>
      <%= f.submit "Assign to Table", class: "btn btn-success btn-sm" %>
    <% end %>

  </li>
<% end %>

app/views/desks/assign_guests.js.erb
$('#available-tables').html('<%= j(render partial: "available_tables") %>');
$('#pending-guests').html('<%= j(render partial: "pending_guests") %>');

app/views/desks/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          New Table
        </div>
        <div class="card-body">
          <%= simple_form_for [@wedding, @desk] do |f| %>
            <%= @desk.errors.full_messages.to_sentence %>
            <div class="mb-3">
              <%= f.label :name, "Table Name:" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= f.label :capacity, "Table Capacity:" %>
              <%= f.number_field :capacity, class: "form-control", min: 6, max: 12 %>
            </div>
            <div class="mb-3">
              <%= f.label :shape, "Table Shape:" %>
              <%= f.select :shape, options_for_select([['Square', 'square'], ['Rectangle', 'rectangle']]), {}, class: "form-control" %>
            </div>
            <div class="d-grid gap-2">
              <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/desks/index.html.erb
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All tables", wedding_desks_path(@wedding), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Seating tables", sitting_plan_wedding_path(@wedding), class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav> -->

<div class="container">
  <div class="m3">
<div class="d-flex justify-content-between">
    <h1 class="beautiful-heading"><span class="orange"><%= @desks.count %></span> wedding tables</h1>
    <%= link_to "+", new_wedding_desk_path(@wedding), class: "btn desk-btn-3", aria_controls: "offcanvasRight", data: { bs_toggle: "offcanvas", bs_target: "#offcanvasNewDesk" } %>
    </div>
    <div class="desk-grid">
      <% @desks.each do |desk| %>
        <div class="desk-card">
          <div class="desk-card-left">
            <h3><%= desk.name %></h3>
            <div class="desk-feature">
              <%= image_tag "#{desk.shape.downcase}.svg" %>
              <p><%= desk.shape.capitalize %> table</p>
            </div>
            <div class="desk-feature">
              <%= image_tag "groupe.svg" %>
              <p>Max. <%= desk.capacity %> guests</p>
            </div>
          </div>
          <div class="desk-card-right">
            <div>
              <div class="desk-gauge-container">
                <div class="desk-gauge">
                  <% desk.taken_seats.times do  %>
                    <div class="desk-gauge-item taken"></div>
                  <% end %>
                  <% desk.remaining_seats.times do  %>
                    <div class="desk-gauge-item"></div>
                  <% end %>
                </div>
                <% if desk.remaining_seats.zero? %>
                  <p class="desk-gauge-info"><strong>COMPLETE</strong></p>
                <% else %>
                  <p class="desk-gauge-info"><strong><%= desk.remaining_seats %></strong> seats left</p>
                <% end %>
              </div>
            </div>

            <%= link_to edit_wedding_desk_path(@wedding, desk), class: "desk-cta", aria_controls: "offcanvasRight", data: { bs_toggle: "offcanvas", bs_target: "#offcanvasEdit-#{desk.id}" } do %>
              See guests list<%= image_tag "arrow.svg" %>
            <% end %>
          </div>
        </div>
        <%= render "desk_show", desk: desk, wedding: @wedding %>

      <% end %>
    </div>


<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNewDesk" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
    <div class="offcanvas-body">
      <div class="desk-show-title">
        <h5 id="offcanvasRightLabel">New Table</h5>
            <%= simple_form_for [@wedding, @desk] do |f| %>
              <%= @desk.errors.full_messages.to_sentence %>
          <div class="desk-card">
                <%= f.label :name, "Table Name:" %>
                <%= f.text_field :name, class: "desk-features" %>
          </div>
          <div class="desk-card">
                <%= f.label :capacity, "Table Capacity:" %>
                <%= f.number_field :capacity, class: "desk-features", min: 6, max: 12 %>
          </div>
          <div class="desk-card">
                <%= f.label :shape, "Table Shape:" %>
                <%= f.select :shape, options_for_select([['Round', 'round'], ['Rectangular', 'rectangular']]), {}, class: "desk-features" %>
          </div>
          <div class="d-grid gap-2">
                <%= f.submit "Submit", class: "tab" %>
          </div>
            <% end %>
        </div>
      </div>
    </div>
</div>

</div>

</div>

app/views/desks/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          New Desk
        </div>
        <div class="card-body">
          <%= simple_form_for [@wedding, @desk] do |f| %>
            <%= @desk.errors.full_messages.to_sentence %>
            <div class="mb-3">
              <%= f.label :name, "Table Name:" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
              <%= f.label :capacity, "Table Capacity:" %>
              <%= f.number_field :capacity, class: "form-control", min: 6, max: 12 %>
            </div>
            <div class="mb-3">
              <%= f.label :shape, "Table Shape:" %>
              <%= f.select :shape, options_for_select([['Square', 'square'], ['Rectangle', 'rectangle']]), {}, class: "form-control" %>
            </div>
            <div class="d-grid gap-2">
              <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/desks/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">
          Desk Details
        </div>
        <div class="card-body">
          <h2 class="card-title"><%= @desk.name %></h2>
          <div class="details">
            <p class="card-text"><strong>Capacity:</strong> <%= @desk.capacity %></p>
            <p class="card-text"><strong>Shape:</strong> <%= @desk.shape %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/families/index.html.erb
<!-- <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All guests by groups", wedding_families_path(@wedding), class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "All guests by persons", wedding_guests_path(@wedding), class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav> -->


<div class="container maincolor">

  <div class="d-flex justify-content-between">
    <h1 class="beautiful-heading"><span class="orange"><%= @wedding.guests.count %></span> Wedding Guests</h1>
    <button class="btn btn-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Add group</button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
      <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">New Group</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <div class="card">
          <div class="card-body">
            <%= simple_form_for([@wedding, @family]) do |f| %>
              <div class="mb-3">
                <%= f.label :name, "Group Name:" %>
                <%= f.text_field :name, class: "form-control" %>
              </div>
              <div class="mb-3">
                <%= f.label :name, "Contact email:" %>
                <%= f.text_field :email, class: "form-control" %>
              </div>
              <div class="mb-3">
                <%= f.label :guests, "Guests", class: "form-label" %>
                <%= f.abyme_for :guests %>
              </div>
              <div class="d-grid gap-2">
                <%= f.submit "Create Group", class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="families-cards-container">
    <% @families.each_with_index do |family, i| %>

      <div class="card"
             data-controller="sal"
             data-sal="zoom-in"
             data-sal-delay="<%= i * 50 %>">
        <div class="card-body">
          <div class="d-flex justify-content-between">

            <h5 class="card-title"><%= family.name %> <span class="space"><%= family.guests.count %> persons</span></h5>
            <div class="d-flex justify-content-between">
              <span class="cursor-pointer m-1" data-bs-toggle="offcanvas" data-bs-target="#offcanvasAdd-<%= family.id %>" aria-controls="offcanvasRight"><i class="fa-solid fa-circle-plus circlepink"></i></span>
              <span class="cursor-pointer m-1" data-bs-toggle="offcanvas" data-bs-target="#offcanvasEdit-<%= family.id %>" aria-controls="offcanvasRight"><i class="fa-solid fa-pen pengolden"></i></span>
            </div>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasEdit-<%= family.id %>" aria-labelledby="offcanvasRightLabel">
              <div class="offcanvas-header">
                <h5 id="offcanvasRightLabel">Edit Group</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
              <div class="offcanvas-body">
                <div class="card-body">
                  <%= simple_form_for([@wedding, family]) do |f| %>
                    <div class="mb-3">
                      <%= f.input :name, class: "form-control" %>
                    </div>
                    <div class="mb-3">
                      <%= f.input :email, class: "form-control" %>
                    </div>
                    <div class="mb-3">
                      <%= f.label :guests, "Guests", class: "form-label" %>
                      <%= f.abyme_for :guests %>
                    </div>
                    <div class="d-grid gap-2">
                      <%= f.submit "Modify Group", class: "btn btn-primary btn-block" %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <%= render "add_guest", family: family, wedding: @wedding %>
          </div>

          <ul class="">
            <% family.guests.each do |guest| %>
              <% if guest.persisted? %>
                <li>
                  <%= guest.first_name %> <%= guest.last_name %>
                  <% if guest.witness %>
                    - <%= guest.gender == "man" ? "🙋‍♂️" : "🙋‍♀️" %> <%= guest.spouse.first_name %>'s witness
                  <% end %>
                  <%= link_to raw('<i class="fa-regular fa-circle-xmark guestcroix"></i>'), wedding_guest_path(@wedding, guest), data: { turbo_method: :delete } %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>

      </div>
    <% end %>
  </div>

</div>

app/views/guests/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "All guests by groups", wedding_families_path(@wedding), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All guests by persons", wedding_guests_path(@wedding), class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">

  <div class="d-flex justify-content-between">
    <h1>All guests by persons</h1>
    <h3>Total: <span class="badge bg-primary"><%= @guests.count %> persons</span></h3>
  </div>

  <div class="row">
  <% @guests.each do |guest| %>
    <div class="card growing p-0 m-3 col-3">
      <div class="card-header">
        <%= guest.first_name %> <%= guest.last_name %>
      </div>
      <div class="card-body">
        <h5 class="card-title mb-3"><%= guest.family.name %></h5>
        <blockquote class="blockquote mb-0">
          <footer class="blockquote-footer">Invited by: <cite title="Source Title"><%= guest.spouse.first_name %> <%= guest.spouse.last_name %></cite></footer>
        </blockquote>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/guests/new.html.erb
<h1>New Guests</h1>
<%= simple_form_for(@guest) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :gender %>
  <%= f.input :age_category %>
  <%= f.input :witness %>
  <%= f.input :status %>
  <%= f.input :family %>
  <%= f.submit %>
<% end %>

app/views/weddings/sitting_plan.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
        <%= link_to "All tables", wedding_desks_path(@wedding), class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Seating tables", sitting_plan_wedding_path(@wedding), class:"nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container m-3">

<h1>My sitting plan</h1>

    <div class="card m-3">
      <div class="card-header">
        Pending Guests
      </div>
      <div class="card-body">
        <h5 class="card-title"> <%= @pending_guests.count %> guest(s) is/are not assigned</h5>
         <ul>
          <% @pending_guests.each do |pending_guest| %>
          <li class="list-group-item">
            <p> <%= pending_guest.first_name %> <%= pending_guest.last_name %> </p>

            <%= simple_form_for [@wedding, GuestDesk.new] do |f| %>
              <div class="form-control d-flex justify-content-start">
                <%= f.input :guest_id, input_html:{value: pending_guest.id}, as: :hidden %>
                <%= f.collection_select :desk_id, @desks, :id, :name, {}, { multiple: false, class: 'form-control' } %>
                <%= f.submit "Assign to Table", class: "btn btn-success btn-sm" %>
              </div>
            <% end %>
          </li>
          <% end %>
        </ul>

      </div>
    </div>

    <div class="card m-3">
      <div class="card-header">
        Avaibles Tables
      </div>
      <div class="card-body">
        <h5 class="card-title"> <%= @desks.count %> tables are availables</h5>
         <ul>
          <% @desks.each do |desk| %>
          <li class="list-group-item">
            <p> <%= desk.name %> : <%= desk.guests.count %> / <%= desk.capacity %> places </p>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
   
  </div>
</div>
</div>