config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"


  resources :weddings, only: [:show] do
    resources :families
    resources :desks
    resources :guest_desks
    resources :guests, except: :delete
    member do
      post 'assign_guests'
      get 'guest_desks/affect', to: 'guest_desks#affect'
      get "sitting_plan", to: "weddings#sitting_plan"
    end
  end


  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'

  # get "desks/new", to: "desks#new"
  get "guests", to: "guests#index"
  get "guest/new", to: "guest#new"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/desk.rb
class Desk < ApplicationRecord
  belongs_to :wedding
  has_many :guest_desks
  has_many :guests, through: :guest_desks

  def taken_seats
    guests.count
  end

  def remaining_seats
    capacity - taken_seats
  end

  def status
    capacity == guests.count ? "COMPLETE" : "PENDING"
  end
end

app/models/family.rb
class Family < ApplicationRecord
  include Abyme::Model

  has_many :guests, dependent: :destroy
  abymize :guests, permit: :all_attributes

  validates :name, presence: true

  def family?
    guests.map(&:last_name).uniq.compact.count == 1
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :family
  belongs_to :spouse
  # belongs_to :guest_desk
  # belongs_to :desk, through: :guest_desk
  has_many :guest_desks, dependent: :destroy
  has_many :desks, through: :guest_desk

  validates :first_name, presence: true

  GENDER = ["woman", "man"]

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/models/guest_desk.rb
class GuestDesk < ApplicationRecord
  belongs_to :desk
  belongs_to :guest
end

app/models/spouse.rb
class Spouse < ApplicationRecord
  belongs_to :wedding
  has_many :guests, dependent: :destroy

  def fullname
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :email, :password, presence: true
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :wedding_accesses, dependent: :destroy
  has_many :weddings, through: :wedding_accesses
end

app/models/wedding.rb
class Wedding < ApplicationRecord
  has_many :spouses, dependent: :destroy
  has_many :guests, through: :spouses
  has_many :desks, dependent: :destroy
  has_many :families, through: :guests
  has_many :guest_desks, through: :desks

  geocoded_by :city_hall
  after_validation :geocode, if: :will_save_change_to_city_hall?

  def countdown_date
    # Jan 5, 2024 15:37:25
    # debugger
    year, month, day_num = day.to_s.split('-')
    "#{Date::MONTHNAMES[month.to_i].first(3).capitalize} #{day_num}, #{year} 00:00:00"
  end

  def not_affected_guests
    assigned_guests = guests.select do |guest|
      !guest.guest_desks.empty?
    end
    guests - assigned_guests
  end
end

app/models/wedding_access.rb
class WeddingAccess < ApplicationRecord
  belongs_to :user
  belongs_to :wedding
  #validates :category, inclusion: { in: CATEGORIES }
end

app/controllers/desks_controller.rb
class DesksController < ApplicationController
  def index
    @desk = Desk.new # Needed to instantiate the form_with
    @wedding = Wedding.find(params[:wedding_id])
    @desks = @wedding.desks
    @desk = Desk.new
  end

  def new
    @wedding = Wedding.find(params[:wedding_id])
    @desk = Desk.new
  end

  def create
    @desk = Desk.new(desk_params)
    @desk.wedding = current_user.weddings.last
    if @desk.save
      selected_guest_ids = params[:desk][:pending_guests]
      @desk.guests << Guest.where(id: selected_guest_ids) if selected_guest_ids.present?
      redirect_to action: "index"
    else
      render :new
    end
  end

  def show
    @wedding = Wedding.find(params[:wedding_id])
    @desk = Desk.find(params[:id])
  end

  def edit
    @wedding = Wedding.find(params[:wedding_id])
    @desk = Desk.find(params[:id])
  end

  def update
    @desk = Desk.find(params[:id])
    if @desk.update(desk_params)
      redirect_to action: "index", notice: 'Table was successfully updated.'
    else
      render :edit
    end
  end

  def assign_guests
    @desk = Desk.find(params[:id])
    @guests = Guest.where(id: params[:desk][:guest_ids])

    if @desk.guests << @guests
      respond_to do |format|
        format.js
      end
    else
      # Handle errors
    end
  end

  private

  def desk_params
    params.require(:desk).permit(:name, :capacity, :shape)
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

  def index
    @wedding = Wedding.find(params[:wedding_id])
    # @guests = @wedding.guests.all
    @guests = Guest.all
    # @family = Family.new
  end

  def new
    @guest = Guest.new # Needed to instantiate the form_with
  end

  def create
    @wedding = Wedding.find(params[:wedding_id])
    @guest = Guest.new(guest_params)
    @guest.save! # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to wedding_families_path(@wedding)
  end

  def destroy
    @wedding = Wedding.find(params[:wedding_id])
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to wedding_families_path(@wedding)
  end

  private

  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :age_category, :gender, :witness, :status, :family_id, :spouse_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def dashboard
    @wedding = current_user.weddings.last
    
    @markers = [
      {
        lat: @wedding.latitude,
        lng: @wedding.longitude
      }
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desks_helper.rb
module DesksHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/guest_desks_helper.rb
module GuestDesksHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spouses_helper.rb
module SpousesHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/abyme/_guest_fields.html.erb
<%# Partial for guest fields %>
<%= f.input :first_name %>
<%= f.input :last_name %>
<%= f.input :gender, collection: Guest::GENDER %>
<%#= f.input :age_category %>
<%= f.input :witness %>
<%#= f.input :status %>
<%= f.label :name, "Invited by:" %>
<%= f.association :spouse, as: :select, label_method: :first_name %>

<%= f.hidden_field :_destroy %>
<%# Partial for guest fields %>

<%= remove_associated_record content: "Remove guest", class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeddingSuccess - Your Ultimate Wedding Planning Solution</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:sal.js@0.8.5/dist/sal.css" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon2.png') %>
  </head>

  <body class="<%= controller_name %>-<%= action_name %>">

    <%= render "shared/flashes" %>

    <% if action_name == "home" || controller_name == "sessions" %>
       <%= yield %>
    <% else %>
      <div class="main-layout-container">
        <%= render "shared/navbar" unless devise_controller? %>
        <div class="main-right-content">
          <%= yield %>
        </div>
      </div>

    <% end %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container" data-controller="countdown" data-countdown-date-value="<%= @wedding.countdown_date %>">
  <h1 class="beautiful-heading">Hello Lucie, your wedding is in <span class="orange" id="demo"></span></h1>
  <hr class="my-4">
</div>

<div class="container dashboard-grid">


  <div class="div">
    <h2 class="beautiful-heading">Celebration</h2>
    <div class="date">
      <p class="ymd">Sept 15, 2023</p>
      <p class="place"> <i class="fa-solid fa-location-dot"> </i><%= @wedding.city_hall %></p>
    </div>
  </div>

  <div class="div">
    <h2 class="beautiful-heading">Spouses</h2>
    <div class="spouse-card">
      <p class="pro">Ms & Mr</p>
      <p class="name">Lucie Petit & Jean Legros</p>
    </div>
  </div>

  <div  class="div">
    <h2 class="beautiful-heading">Location</h2>
    <div style="width: 100%; height: 236px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>

  <div class="div d-flex justify-content-between">
    <div class="w-100 me-3">
      <h2 class="beautiful-heading">Guests</h2>
      <div class="stats-card">
        <p class="stat"><%= @wedding.guests.count %></p>
        <p class="stat-info">Guests</p>
      </div>
    </div>
    <div class="w-100 ms-3">
      <h2 class="beautiful-heading">Tables</h2>
      <div class="stats-card">
        <p class="stat"><%= @wedding.desks.count %></p>
        <p class="stat-info">Tables</p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <h2 class="beautiful-heading">Dress code</h2>
  <div class="container dashboard-grid-three">

    <div class="spouse-card-pic align-items-center d-flex flex-column justify-content-center text-center square">
      <h3>Blue</h3>
    </div>

    <div class=" align-items-center d-flex flex-column justify-content-center text-center square">
      <img src="<%= image_path "robeb.jpg" %>" class="d-block dress-img-carousel" alt="...">
    </div>

    <div class="spouse-card-pic align-items-center d-flex flex-column justify-content-center text-center square">
      <h3>Chic</h3>
    </div>

    <div class=" align-items-center d-flex flex-column justify-content-center text-center square">
      <img src="<%= image_path "costumeb.jpg" %>" class="d-block dress-img-carousel" alt="...">
    </div>

    <div class="spouse-card-pic align-items-center d-flex flex-column justify-content-center text-center square">
      <h3>Fancy</h3>
    </div>

    <div class=" align-items-center d-flex flex-column justify-content-center text-center square">
      <img src="<%= image_path "escarpinb.jpg" %>" class="d-block dress-img-carousel" alt="...">
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<%= render "shared/navbarhome" %>

<div class="banner">
  <div class="container">
    <h1> <strong>Wedding Success</strong> </h1>
    <p>Plan your wedding in just few clicks</p>
    <%= link_to "START NOW", dashboard_path, class: "btn btn-ghost" %>
  </div>

  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item">
        <%= image_tag"pexel5.jpg", class:"d-block w-100", alt:"..."%>
      </div>
      <div class="carousel-item active">
        <%= image_tag"pexel6.jpg", class:"d-block w-100", alt:"..."%>
      </div>
    </div>
  </div>
</div>

<div class="containerhome">
  <div class="row m-3 align-items-center justify-content-around">
    <div class="col-sm-4 rounded d-block container-img-home">
      <%= image_tag"pexel7.jpg", class:"center d-block w-100 img-home", alt:"..."%>
    </div>
    <div class="col-sm-4">
      <h2>All-in-One Wedding Solution</h2>
      <p>From finding the perfect venue to selecting vendors, managing your guest list, and tracking your budget, Wedding Success is your one-stop destination for everything you need to organize an unforgettable wedding. Every wedding is unique, and we understand that. With our platform, you can customize every detail to match your vision and style.</p>
    </div>
  </div>
  <div class="row m-3 align-items-center justify-content-around">
    <div class="col-sm-4">
      <h2>Stress-Free Wedding Planning</h2>
      <p>Expert Guidance: Our team of experienced wedding planners and experts is here to provide you with guidance, tips, and inspiration, ensuring that your wedding day is as perfect as you've always imagined. Say goodbye to wedding planning stress. Our intuitive tools and resources make the entire process seamless and enjoyable, allowing you to focus on what truly matters—celebrating your love.</p>
    </div>
    <div class="col-sm-4 rounded d-block container-img-home">
      <%= image_tag"pexel1.jpg", class:"center d-block w-100", alt:"..."%>
    </div>
  </div>
</div>


<%= render "shared/footer" %>

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%# <a href="#"><i class="fab fa-github"></i></a> %>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Wedding Success <i class="fa-solid fa-copyright"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-gold wedding-navbar">
    <%= link_to root_path, class: "items-centerauto text-decoration-none" do %>
      <%= image_tag "logo.png", id: "sidebar-logo" %>
    <% end %>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="p-1">
        <%= link_to dashboard_path, class: "nav-link #{"active" if controller_name == "pages" && action_name == "dashboard"}" do %>
          <div class="d-flex align-items-center justify-content-center">
            <i class="fa-solid fa-house me-3"></i>
            <p>Dashboard</p>
          </div>
        <% end %>
      </li>
      <li class="p-1">
        <%= link_to wedding_families_path(@wedding), data: {turbo: false}, class: "nav-link #{"active" if controller_name == "families" && action_name == "index"}" do %>
          <div class="d-flex align-items-center justify-content-center">
            <i class="fa-solid fa-users me-3"></i>
            <p>Guests</p>
          </div>
        <% end %>
      </li>
      <li class="p-1">
        <%= link_to wedding_desks_path(@wedding), class: "nav-link #{"active" if controller_name == "desks" && action_name == "index"}" do %>
          <div class="d-flex align-items-center justify-content-center">
            <i class="fa-solid fa-chair me-3"></i>
            <p>Tables</p>
          </div>
        <% end %>
      </li>
    </ul>
    <div class="d-flex align-items-center justify-content-around">
      <%= image_tag "https://images.pexels.com/photos/5876695/pexels-photo-5876695.jpeg?auto=compress&cs=tinysrgb&w=800", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

      <p class="p-2"><%= link_to ('<i class="fa-solid fa-right-from-bracket"></i>').html_safe, destroy_user_session_path, data: { turbo_method: :delete }  %></p>
    </div>
  </div>
</nav>

app/views/shared/_navbarhome.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" width="30" height="24">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="item">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
            </li>
            <li class="nav-item">
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://images.pexels.com/photos/5876695/pexels-photo-5876695.jpeg?auto=compress&cs=tinysrgb&w=800", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Log out",destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>